ID of route is not set when onException is used
When building a route like this:

....
public void configure() {

from("jms:fileIn?transacted=true")
  .onException(UnmarshalException.class)
   .handled(true)
    .bean(FileProcessExceptionBean.class,"handleException")
.end()
.id("fileMapping")
.transacted()
.process(new FileProcessor())
.to("jms:fileOut");

}


the id is not set. When the onException-section is removed, the id is set correctly