TestTCTLSeparatedProtocol is broken
Some of the tests in TestTCTLSeparatedProtocol throws a NullPointedException that is catched, logged and not rethrown. This means the tests don&amp;apos;t fail even though an unexpected exception is thrown.