EndpointInterceptor.afterCompletion is not always invoked
afterCompletion&amp;apos;s javadoc states that it will be called on any outcome of endpoint invocation, allowing for proper resource cleanup. There is however a case where handleRequest() successfully completes, but afterCompletion() is never invoked. This happens whenever an exception occurs and no EndpointExceptionResolver is able to resolve the exception.






MessageDispatcher.java






// within dispatch()&amp;apos;s last catch block




catch (Exception ex) {




  Object endpoint = mappedEndpoint != null ? mappedEndpoint.getEndpoint() : null;




  processEndpointException(messageContext, endpoint, ex); // exception is rethrown here..




  triggerHandleResponse(mappedEndpoint, interceptorIndex, messageContext);




  triggerAfterCompletion(mappedEndpoint, interceptorIndex, messageContext, ex); // .. and afterCompletion() is never invoked




}






