TeeOutputStream does not call branch.close() when main.close() throws an exception
TeeOutputStream.close() looks like this:
TeeOutputStream.java


    /**

     * Closes both streams. 

     * @throws IOException if an I/O error occurs

     */

    @Override

    public void close() throws IOException {

        super.close();

        this.branch.close();

    }



It is obvious that this.branch.close() is not executed when super.close() raises an exception. super.close() may in fact raise an IOException since ProxyOutputStream.handleIOException(IOException) is not overridden.