"Perform tests" problem using app engine datastore.
Add a project, setup the database using the "persistence setup --provider DATANUCLEUS --database GOOGLE_APP_ENGINE" command, an entity, a field and a controller. 
The "perform tests" command produces this error, which is also reported by other forum members(please check the forum post):
-------------------------------------------------------
  T E S T S
 -------------------------------------------------------
 Running org.firstats.web.domain.CategoryIntegrationTest
 2010-11-07 18:10:55,583 [main] ERROR DataNucleus.Transaction - Opera
tion rollback failed on resource: org.datanucleus.store.appengine.DatastoreXARes
ource@e63606, error code UNKNOWN and transaction: [DataNucleus Transaction, ID=Xid=    enlisted resources=[org.datanucleus.store.appengine.DatastoreXAResource@18ed77a]]
 2010-11-07 18:14:58,383 [main] ERROR DataNucleus.Transaction - Opera
tion rollback failed on resource: org.datanucleus.store.appengine.DatastoreXARes
ource@15af049, error code UNKNOWN and transaction: [DataNucleus Transaction, ID=Xid=   enlisted resources=[org.datanucleus.store.appengine.DatastoreXAResource@15af049]]
 Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.5
8 sec &lt;&lt;&lt; FAILURE!
 Results :
 Tests in error:
   testCountCategorys(org.firstats.web.domain.CategoryIntegrationTes
)
 Tests run: 9, Failures: 0, Errors: 1, Skipped: 0
 [INFO] ------------------------------------------------------------
-----------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------
-----------
[INFO] There are test failures.