NoWorkFoundStepExecutionListener doesn&apos;t fail the step
The NoWorkFoundStepExecutionListener throws an exception from an AfterStep method.  However, throwing an exception from an AfterStep only results in the exception being logged and has no impact on the status of the step.  Instead, the AfterStep method should return ExitStatus.FAILED.