Camel XMPP doesn&apos;t use a DNS resolver to look at SRV records
Camel XMPP doesn&amp;apos;t use a DNS resolver to look at SRV records, whereas in 2.14.1 it did.
In 2.15.0, ConnectionConfiguration calls DNSUtil.resolveXMPPDomain(serviceName) which runs this code:
DNSUtil.java


public static List&lt;HostAddress&gt; resolveXMPPDomain(final String domain) {

        if (dnsResolver == null) {

            List&lt;HostAddress&gt; addresses = new ArrayList&lt;HostAddress&gt;(1);

            addresses.add(new HostAddress(domain, 5222));

            return addresses;

        }

        return resolveDomain(domain, &amp;apos;c&amp;apos;);

    }



dnsResolver is never initialised, so it returns the service name, in my case &amp;apos;jabberzac.org&amp;apos;, instead of the actual XMPP server from the SRV Record, &amp;apos;xmpp.jabberzac.org&amp;apos;, which then causes a timeout.
The dnsResolver is meant to be instantiated in init(), which is meant to be called by SmackConfiguration, but never is.
DNSUtil.java


    /**

     * Initializes DNSUtil. This method is automatically called by SmackConfiguration, you don&amp;apos;t

     * have to call it manually.

     */

    public static void init() {

        final String[] RESOLVERS = new String[] { "javax.JavaxResolver", "minidns.MiniDnsResolver",

                        "dnsjava.DNSJavaResolver" };

        for (String resolver :RESOLVERS) {

            DNSResolver availableResolver = null;

            String resolverFull = "org.jivesoftware.smack.util.dns" + resolver;

            try {

                Class&lt;?&gt; resolverClass = Class.forName(resolverFull);

                Method getInstanceMethod = resolverClass.getMethod("getInstance");

                availableResolver = (DNSResolver) getInstanceMethod.invoke(null);

                if (availableResolver != null) {

                    setDNSResolver(availableResolver);

                    break;

                }

            }

            catch (ClassNotFoundException|NoSuchMethodException|SecurityException|IllegalAccessException|IllegalArgumentException|InvocationTargetException e) {

                LOGGER.log(Level.FINE, "Exception on init", e);

            }

        }

    }



2.14.1 doesn&amp;apos;t seem to have this problem as DNSUtil class in 2.14.1 doesn&amp;apos;t have an init() function which is meant to be &amp;apos;automatically called&amp;apos;, it just has a static code block:



    static {

        try {

            Hashtable env = new Hashtable();

            env.put("java.naming.factory.initial", "com.sun.jndi.dns.DnsContextFactory");

            context = new InitialDirContext(env);

        }

        catch (Exception e) {

            // Ignore.

        }

    }


