Throwing exceptions inside a ChunkListener results in endless loop
If an exception is thrown in beforeChunk in a ChunkListener and the job is configured with skips (but not to skip the exception that is thrown from the ChunkListener) it will result in an endless loop. Same will happen if you have configured your job for retries.
If neither retry nor skip is configured, the job will end with ExitStatus.FAILED, as expected. Which makes me suspect the issue is in the exception handling in some of the components added when skip or retry comes into play.
I&amp;apos;ve attached two files based on the Spring Batch template from STS that can be dropped in to reproduce the issue.